version: '3.4'

services:
  app:
    image: registry.gitlab.com/khacviet.dev/project-backend:latest
    volumes:
      - ./log:/app/log
    environment:
      - ENVIRONMENT=${ENVIRONMENT}
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT={REDIS_PORT}
      - REDIS_PASSWORD={REDIS_PASSWORD}
      - ACCESS_TOKEN_SERCRET_KEY=${ACCESS_TOKEN_SERCRET_KEY}
      - GMAIL_USER=${GMAIL_USER}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SERCRET_KEY=${GOOGLE_SERCRET_KEY}
      - GOOGLE_REFRESH_TOKEN=${GOOGLE_REFRESH_TOKEN}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - AWS_SECRET_KEY=${AWS_SECRET_KEY}
      - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_S3_BUCKET=${AWS_S3_BUCKET}
    ports:
      - '${PORT}:${PORT}' # phần này ta định nghĩa ở file .env nhé
    restart: unless-stopped
